import type {LessonView} from "../../lib/types";
import {SplitFloor,RefractionLab,BuilderSteps} from "./Day31Visuals";
const subjects:Record<string,{name:string;time:string;line:string;image?:string;alt?:string}>={
 mathematics:{name:"Mathematics",time:"9:30–10:20",line:"Same floor. A new way to see it."},
 writing:{name:"Writing",time:"10:30–11:20",line:"Show the link.",image:"library-readers.jpg",alt:"Imagined school library: two classmates looking closely at illustrated books."},
 french:{name:"French",time:"11:20–11:45",line:"Meet me at the library.",image:"library-readers.jpg",alt:"Two classmates discussing a book in an imagined library scene."},
 science:{name:"Science",time:"11:45–12:20",line:"Light takes a turn."},
 history_geography:{name:"History & geography",time:"1:00–1:35",line:"Who could say stop?",image:"tribune-veto.jpg",alt:"Artist’s imagined Roman scene: a tribune raises a hand toward an official, with citizens beside him."},
 computer_science:{name:"AI Builder",time:"1:35–2:35",line:"Give your car its close-up.",image:"hover-tested-poster.jpg",alt:"Actual Blender render of our reference car, used to test today’s settings. This is not Atticus’s submitted model."},
 literature:{name:"Literature",time:"2:45–3:20",line:"Make the clue and idea fit."}
};
function SubjectVisual({subject}:{subject:string}){
 if(subject==="mathematics")return <SplitFloor interactive/>;
 if(subject==="science")return <RefractionLab/>;
 if(subject==="writing")return <div className="day31-source"><span className="eyebrow">YOUR SOURCE · INVENTED LIBRARY RECORD</span><table><thead><tr><th>One-hour visit</th><th>Visitors</th><th>Borrowed a graphic novel</th></tr></thead><tbody><tr><th>First Tuesday · no display</th><td>20</td><td>5</td></tr><tr><th>Second Tuesday · new display</th><td>20</td><td>12</td></tr></tbody></table><p>We do not know whether the same students visited both times. The picture illustrates the setting; this table gives the facts.</p></div>;
 if(subject==="french")return <div className="day30-talk"><p><b>ASK · Où means where</b>Où est-ce que tu vas lire ?<small>Where are you going to read?</small></p><p><b>REPLY · Use je for yourself</b>Je vais lire à la bibliothèque.<small>I am going to read at the library.</small></p><p><b>A SHARED PLAN · Nous means we</b>Nous allons lire ensemble.<small>We are going to read together.</small></p></div>;
 if(subject==="history_geography")return <div className="day30-comparison"><div><b>Plebeians</b><p>Choose tribunes to represent their interests.</p></div><div><b>Tribune</b><p>Can use a veto to stop an official action.</p></div><div><b>Still unequal</b><p>That power does not give everyone equal rights.</p></div><small>The scene is an imagined reconstruction. Its raised hand helps show the idea of stopping an action.</small></div>;
 if(subject==="computer_science")return <BuilderSteps/>;
 return <div className="day31-clue"><span className="eyebrow">AN INVENTED MYSTERY · NOT THE WESTING GAME</span><h4>“Mina’s shoes were wet.”</h4><div className="day30-comparison"><div><b>Idea 1</b><p>Rain outside could wet her shoes.</p></div><div><b>Idea 2</b><p>Spilled water inside could wet them too.</p></div><div><b>Still unknown</b><p>The wet shoes do not tell us which happened.</p></div></div><p>Both ideas fit the same detail. A theory about being quiet does not explain wet shoes.</p></div>;
}
export function Day31Lesson({lesson,onExplore}:{lesson:LessonView;onExplore:()=>void}){
 const subject=subjects[lesson.subject],number=Object.keys(subjects).indexOf(lesson.subject)+1;
 return <div className="day29-lesson day30-lesson day31-lesson">
 <header className="day29-title-page"><div className="day29-title-copy"><span className="eyebrow">WEDNESDAY · DAY 31 · CHAPTER {String(number).padStart(2,"0")}</span><p className="day29-subject">{subject.name}<span>{subject.time}</span></p><h2>{subject.line}</h2><p>{lesson.learning_objectives[0]}</p><div className="day29-route"><span>1 · Learn</span><span>2 · See examples</span><span>3 · Type & hand in</span></div></div>{subject.image&&<img className="day30-cover" src={`/lesson-visuals/2026-10-07/${subject.image}`} alt={subject.alt}/>}</header>
 <aside className="day30-paperless"><strong>Your work stays on screen.</strong> Read, try the examples, then open Practice. Click <strong>Hand in my answers</strong> and check the receipt. No paper needed.</aside>
 <section className="day29-section"><span className="eyebrow">01 / LEARN THE IDEA</span><h3>{lesson.lesson_title}</h3><p className="day29-purpose">{lesson.why_it_matters}</p><details className="day31-continuity"><summary>Where we left off</summary><p>{lesson.previous_learning}</p></details>
 <div className="day29-vocabulary">{lesson.vocabulary.map(w=><div key={w.term}><strong>{w.term}</strong><p>{w.definition}</p></div>)}</div>
 <div className="day29-instruction">{lesson.written_instruction.split(/\n+/).filter(Boolean).map((p,i)=>{const separator=p.indexOf(' · '),stop=p.indexOf('. ');const at=separator>=0?p.indexOf('. ',separator):stop;return <div className="day31-teach-step" key={i}><p>{at>=0&&at<105?<><strong>{p.slice(0,at+1)}</strong>{p.slice(at+1)}</>:p}</p>{i===(lesson.subject==="computer_science"?4:lesson.subject==="science"?3:lesson.subject==="mathematics"?3:1)&&<SubjectVisual subject={lesson.subject}/>}</div>;})}</div>
 {lesson.subject==="computer_science"&&<details className="day30-guide"><summary>Parent: setup and test notes</summary><p>The new Bevel settings and a 960 × 600 Cycles CPU render were tested in Blender 5.2 using our reference car. The image above is that test render. We have not opened Atticus’s local file or measured render speed on his Snapdragon laptop. Start by checking his actual saved file. No installation or new account is assigned. Save and report a blocker if the screen differs.</p><p>The project remains ongoing. A progress hand-in completes this lesson block, not the whole car project.</p></details>}
 </section>
 <section className="day29-section"><span className="eyebrow">02 / SEE HOW IT WORKS</span><h3>Follow a complete example.</h3>{lesson.worked_examples.map((e,i)=><article className="day29-model" key={e.title}><span className="eyebrow">EXAMPLE {i+1}</span><h4>{e.title}</h4><p>{e.problem}</p><div className="day29-result"><strong>Worked result</strong><p>{e.solution}</p></div><p><strong>Why it works:</strong> {e.explanation}</p></article>)}</section>
 <section className="day29-next"><div><span className="eyebrow">03 / YOUR TURN</span><h3>{lesson.subject==="computer_science"?"Record the work you actually did.":"Now try it yourself."}</h3><p>Your answer boxes and hand-in button are in Practice.</p></div><button className="button dark" onClick={onExplore}>Open Practice →</button></section>
 {(lesson.source_references??[]).length>0&&<details className="day31-sources"><summary>Lesson sources</summary>{(lesson.source_references??[]).map((url,i)=><p key={url}><a href={url} target="_blank" rel="noreferrer">{lesson.subject==="computer_science"?["Blender: Bevel modifier","Blender: saving project files","Blender: output files"][i]:lesson.subject==="science"?"Institute of Physics: refraction":"OpenStax: the Roman Republic"} ↗</a></p>)}</details>}
 </div>;
}
